import logging
import pandas as pd
from utils import arquivar_csv
from actions.upsert_data.pg_upsert_utils import bulk_upsert

TABLE_COLUMNS = [
    "MF_ID", "EMP_ID", "CLI_ID", "FORN_ID", "PROJ_ID", "CR_ID",
    "USU_ID", "TIPO", "SUBTIPO", "VALOR", "VALOR_COM_IMPOSTOS",
    "VALOR_SEM_RET", "VALOR_MULTA", "VALOR_JUROS", "VALOR_PAGO",
    "SITUACAO", "NOTA_FISCAL", "NOTA_FISCAL_ORD", "RPS",
    "DATA_REFERENCIA", "DATA_VENCIMENTO", "DATA_VENC_ORIG",
    "DT_PAGAMENTO", "DATA_EMISSAO", "RGR_ID", "OBSERVACAO",
    "DESCRICAO", "CODIGO_SERVICO", "CATEGORIA_ID_MYFINANCE",
    "CENTRO_RECEITA_ID_MYFINANCE", "CONTA_RECEBIMENTO_ID_MYFINANCE",
    "NFE_COD_VER", "NOTIFICACAO", "MYFINANCE_ID", "READONLY",
    "INCLUIDO_EM", "ALTERADO_EM", "AUX", "FAT_ID",
    "CONTA_COBRANCA_ID_COBRATO", "TEMPLATE_ID_EMITES",
    "BILLIMATIC_ID", "UDF1", "UDF2", "UDF3", "UDF4", "UDF5", "UDF6",
    "UDF7", "UDF8", "UDF9", "UDF10", "ALIQ_APROX",
    "CONTA_RECEBIVEIS_ID_MYFINANCE", "MODELO_COBRANCA_ID_COBRATO",
    "OMIE_ID", "OMIE_SERVICO", "OMIE_COD_INTERNO", "OMIE_ID_ANTIGO",
    "OMIE_COD_INTERNO_ANTIGO", "OMIE_SERVICO_ANTIGO", "IND_FINAL",
    "C_IND_OP", "TP_OPER", "TP_ENTE_GOV", "IND_DEST",
    "TP_CHAVE_DFE", "X_TIPO_CHAVE_DFE", "CHAVE_DFE",
    "C_MUN_DOC_FISCAL", "N_DOC_FISCAL", "X_DOC_FISCAL", "N_DOC",
    "X_DOC", "CPF_FORN_DOC", "CNPJ_FORN_DOC", "NIF_FORN_DOC",
    "NAO_NIF", "NOME_FORN_DOC", "DT_EMISSAO_DOC_DED",
    "DT_COMPETENCIA_DOC_DED", "VL_BASE_IS", "VL_IS", "VL_BASE_CBS",
    "VL_CBS", "VL_BASE_IBS", "VL_IBS_ESTADUAL", "VL_IBS_MUNICIPAL",
    "VALOR_COM_IMPOSTOS_IVA", "ALIQ_IS", "ALIQ_CBS",
    "ALIQ_IBS_ESTADUAL", "ALIQ_IBS_MUNICIPAL", "TRIBUTACAO_RPS",
    "FONTE_CARGA_TRIBUT", "CODIGO_CEI", "MUNICIPIO_PRESTACAO",
    "NUMERO_ENCAPSULAMENTO", "EXIGIBILIDADE_SUSPENSA",
    "PGTO_PARCELADO_ANTECIPADO", "NCM", "NBS", "C_CLASS_TRIB",
    "C_CLASS_TRIB_REG", "TP_REE_REP_RES", "DESC_REE_REP_RES",
    "VL_REE_REP_RES", "C_LOC_PRESTACAO", "SERIE", "DISCRIMINACAO",
    "INSCRICAO_PRESTADOR", "CARGA_TRIBUTARIA"
]

TABLE_NAME = "FATURAMENTO"
PK_COLUMNS = ["MF_ID"]
DATE_COLUMNS = [
    "DATA_REFERENCIA", "DATA_VENCIMENTO", "DATA_VENC_ORIG",
    "DT_PAGAMENTO", "DATA_EMISSAO", "INCLUIDO_EM", "ALTERADO_EM",
    "DT_EMISSAO_DOC_DED", "DT_COMPETENCIA_DOC_DED",
]
BOOLEAN_COLUMNS = []


def upsert_data(df: pd.DataFrame, table_name: str, csv_file_path: str):
    bulk_upsert(
        df=df, table_name=TABLE_NAME,
        all_columns=TABLE_COLUMNS, pk_columns=PK_COLUMNS,
        date_columns=DATE_COLUMNS, boolean_columns=BOOLEAN_COLUMNS,
        csv_file_path=csv_file_path,
        archive_func=arquivar_csv, archive_name=table_name,
    )
