import logging
import pandas as pd
from utils import arquivar_csv
from actions.upsert_data.pg_upsert_utils import bulk_upsert

TABLE_COLUMNS = [
    "PROJ_ID", "DEPT_ID", "TAXA_ID", "EMP_ID", "CLI_ID", "HE_ID_FAT",
    "HE_ID_PAG", "DT_INICIO", "DT_FIM", "DT_INICIO_INF", "DT_FIM_INF",
    "B_DT_INICIO", "B_DT_FIM", "CODIGO", "NOME", "DESCRICAO", "ATIVO",
    "USU_EMP_ID", "USU_CLI_ID", "PROJ_ID_PAI", "TIPO_DE_PROJETO",
    "CR_ID", "RGR_HORAS_TRANSPORTE", "RGR_HORAS_EXTRAS",
    "RGR_CRIAR_ATIVIDADES", "RGR_DELEGAR_ATIVIDADES",
    "RGR_APONTAR_ATIVIDADES", "RGR_INSTRUCOES_TRANSPORTE", "VALOR",
    "ALIQ_COFINS", "ALIQ_PIS", "ALIQ_ISS", "ALIQ_IRRF", "ALIQ_CSLL",
    "IND_IMPOSTOS_NA_TAXA_FAT", "COM_ID", "COM_ID_HIS", "INCLUIDO_EM",
    "ALTERADO_EM", "UDF1", "UDF2", "UDF3", "UDF4", "UDF5", "UDF6",
    "UDF7", "UDF8", "UDF9", "UDF10", "TRABALHO_PREVISTO",
    "TRABALHO_REALIZADO", "TRABALHO_FALTANDO", "TRABALHO_APONTADO",
    "DURACAO_PREVISTA", "B_TRABALHO_PREVISTO", "BCWP", "BCWS", "VA_VP",
    "CR_VC", "NUM_PROPOSTA", "TIPO_DI", "CLASSE", "PRIORIDADE_OS",
    "IND_HR_FAT_ATIV_OS", "WORKFLOW", "DEFPESQ_ID",
    "IND_HORAS_FATURAVEIS", "PROB_FECHAMENTO", "WKF_STEP",
    "WKF_STEP_DESC", "DT_ENCERRAMENTO", "IND_APO_BLOQ", "IND_FAT_BLOQ",
    "IND_PLAN_BLOQ", "LIMITE_MINUTOS", "VERSAO_CRONOGRAMA",
    "IND_OS_HABILITADO", "IND_CALCULO_MANUAL", "IND_DT_PREV_ATUALIZADA",
    "TRELLO_BOARD_ID", "TRELLO_LIST_ID_INICIO", "TRELLO_LIST_ID_FIM",
    "BILLIMATIC_CONTRATO", "BILLIMATIC_CONTRATO_ID",
    "IND_BILLIMATIC_PREV", "UDF11", "UDF12", "UDF13", "UDF14", "UDF15",
    "UDF16", "UDF17", "UDF18", "UDF19", "UDF20",
    "IND_BILLIMATIC_FAT_AUTOMATICO", "BILLIMATIC_MODELO_FAT_ID",
    "ENDERECO", "JIRA_PROJ_ID", "JIRA_RECURSO", "JIRA_DT_INICIO",
    "JIRA_ACCOUNT_ID", "JIRA_CRONOGRAMA", "AGILE_CONFIG",
    "AGILE_IND_APONTAMENTO", "AGILE_IND_PROJETO", "AGILE_PROJ_ID",
    "CFG_EPT_APONTAMENTO", "ESCOPO_VERSAO"
]

TABLE_NAME = "PROJETOS"
PK_COLUMNS = ["PROJ_ID"]
DATE_COLUMNS = [
    "DT_INICIO", "DT_FIM", "DT_INICIO_INF", "DT_FIM_INF",
    "B_DT_INICIO", "B_DT_FIM", "INCLUIDO_EM", "ALTERADO_EM",
    "DT_ENCERRAMENTO", "JIRA_DT_INICIO", "ESCOPO_VERSAO",
]
BOOLEAN_COLUMNS = [
    "IND_IMPOSTOS_NA_TAXA_FAT", "IND_HR_FAT_ATIV_OS",
    "IND_HORAS_FATURAVEIS", "IND_APO_BLOQ", "IND_FAT_BLOQ",
    "IND_PLAN_BLOQ", "IND_OS_HABILITADO", "IND_CALCULO_MANUAL",
    "IND_DT_PREV_ATUALIZADA", "IND_BILLIMATIC_PREV",
    "IND_BILLIMATIC_FAT_AUTOMATICO", "AGILE_IND_APONTAMENTO",
    "AGILE_IND_PROJETO",
]


def upsert_data(df: pd.DataFrame, table_name: str, csv_file_path: str):
    bulk_upsert(
        df=df, table_name=TABLE_NAME,
        all_columns=TABLE_COLUMNS, pk_columns=PK_COLUMNS,
        date_columns=DATE_COLUMNS, boolean_columns=BOOLEAN_COLUMNS,
        csv_file_path=csv_file_path,
        archive_func=arquivar_csv, archive_name=table_name,
    )
