import logging
import os
import pandas as pd
from actions.upsert_data.pg_upsert_utils import bulk_upsert

TABLE_COLUMNS = [
    "CODIGO_PROJETO", "DT_FIM_PROJETO", "DT_INICIO_PROJETO",
    "NOME_PROJETO", "VALOR_PROJETO", "ATIVO", "PROJ_ID", "DT_CALCULO",
    "VALOR_CUSTO_TOTAL_ORCADO_HORAS", "VALOR_CUSTO_TOTAL_REAL_HORAS",
    "VALOR_CUSTO_TOTAL_FALTANDO_HORAS",
    "VALOR_CUSTO_TOTAL_ORCADO_DESPESAS",
    "VALOR_CUSTO_TOTAL_REAL_DESPESAS",
    "VALOR_CUSTO_TOTAL_FALTANDO_DESPESAS", "ATIV_ID", "NOME_ATIVIDADE",
    "B_DT_FIM_ATIVIDADE", "B_DT_INICIO_ATIVIDADE", "DT_FIM_ATIVIDADE",
    "DT_INICIO_ATIVIDADE", "DURACAO_PREVISTA_HORAS",
    "TRABALHO_TOTAL_APONTADO_ATIVIDADE",
    "TRABALHO_TOTAL_FALTANDO_ATIVIDADE",
    "TRABALHO_TOTAL_PREVISTO_ATIVIDADE", "ATRIB_ID", "PROJREC_ID",
    "USU_ID", "TRABALHO_RECURSO_APONTADO_ATIVIDADE",
    "TRABALHO_RECURSO_FALTANDO_ATIVIDADE",
    "TRABALHO_RECURSO_PREVISTO_ATIVIDADE", "PERC_ALOCACAO",
    "NOME_RECURSO", "DESCRICAO", "TX_ID_RECURSO"
]

TABLE_NAME = "RELATORIO_PSO_PLANEJADO"
PK_COLUMNS = ["PROJ_ID", "ATIV_ID", "ATRIB_ID"]
DATE_COLUMNS = [
    "DT_FIM_PROJETO", "DT_INICIO_PROJETO", "DT_CALCULO",
    "B_DT_FIM_ATIVIDADE", "B_DT_INICIO_ATIVIDADE",
    "DT_FIM_ATIVIDADE", "DT_INICIO_ATIVIDADE",
]
BOOLEAN_COLUMNS = ["ATIVO"]


def upsert_data(df: pd.DataFrame, table_name: str, csv_file_path: str):
    bulk_upsert(
        df=df, table_name=TABLE_NAME,
        all_columns=TABLE_COLUMNS, pk_columns=PK_COLUMNS,
        date_columns=DATE_COLUMNS, boolean_columns=BOOLEAN_COLUMNS,
    )
    if os.path.exists(csv_file_path):
        os.remove(csv_file_path)
        logging.info(f"Arquivo CSV {csv_file_path} excluido com sucesso.")
